### PR TITLE
Importer improvements

### PR DESCRIPTION
**Pull request by akbertram**
A number of small fixes and refactoring for the importer.

### CODE REVIEW

**Comment by akbertram** [comment]
@nickdickinson is there a way to get the checks running on pull requests?

**Comment by nickdickinson** [comment]
It is possible to do. Right now it will for pull requests to only 'main' and 'master' but I believe if we remove that specification from tic.yml it will run on any pull request. Shall I do that?

**Comment by akbertram** [comment]
Sounds good!

**Comment by nickdickinson** [comment]
Great, I'll make the change to 4.32 so when we merge it to main in the next release it will start in earnest. For now, I've run a job manually against the importer-improvements branch.

**Comment by nickdickinson** [comment]
Hi Alex, the workflow failed because of a warning about the parentIdColumn argument not being added to the Roxygen:
https://github.com/bedatadriven/activityinfo-R/actions/runs/4032578835/jobs/6932550069

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'importTable'
    ‘parentIdColumn’

**Comment by nickdickinson** [comment]
Hi Alex, there is one conflicting file in this branch on line 88 in import.R:
```
<<<<<<< importer-improvements
                 paste(head(parentId[!validParentIds]), collapse = ", ")))
=======
                 paste(head(parentIds[!validParentIds]), collapse = ", ")))
>>>>>>> version-4.32
```

**Comment by nickdickinson** [comment]
I've resolved the conflict and will proceed to merge after testing.

**Pull request merged**
